export {
  BranchIsolationError,
  assertCurrentBranch,
  assertWorkingTreeClean,
  branchExists,
  buildBranchName,
  buildTaskWorktreePath,
  describeDirtyWorkingTree,
  ensureFeatureBranch,
  ensureTaskWorktree,
  getCurrentBranch,
  getHeadCommitSha,
  isBranchIsolationError,
  isGitRepo,
  projectSupportsTaskWorktrees,
  projectUsesSharedBranchIsolation,
  restorePersistedBranch,
  slugifyTitle,
  syncBranchWithBase,
  validateBranchName,
  workingTreeClean,
  type BranchBaseSyncResult,
  type EnsureFeatureBranchInput,
  type EnsureFeatureBranchResult,
  type EnsureTaskWorktreeInput,
  type EnsureTaskWorktreeResult,
  type RestorePersistedBranchInput,
  type SyncBranchWithBaseInput,
} from "@aif/shared";
